### ISSUE TITLE
Outstanding HTML/CSS

### ISSUE THREAD

**Issue by Grace-YuGuo** [Grace-YuGuo/rock-paper-scissors-lizard-spock-game#13]
Tasks:

- tablet/desktop views
- dropdown toggle for the rules dropdown
- the five options need finishing (updating respective icons, colours, and hover states)
- either the start game buttons or the game area need to be hidden based on game stage
- finishing touches designwise

Acceptance creteria:
- HTML/ CSS related code all finished up
- JavaScript related part to leave it to next stage

**Comment by Mah-N** [comment]
@Grace-YuGuo I will work on these two-
1. tablet/desktop views
2. dropdown toggle for the rules dropdown

**Comment by Grace-YuGuo** [comment]
I completed some of the tablet and laptop view, to merge. You can continue if you need or redo this part.

**Comment by Grace-YuGuo** [comment]
The third task:
Completed:
The five options need finishing (updating respective icons, colours, and hover states).
 Update the startButton hoverstates

**Comment by Grace-YuGuo** [comment]
The fourth task:
either the start game buttons or the game area need to be hidden based on game stage.

Solution: added hidden and visible class in css file to use.

**Comment by Grace-YuGuo** [comment]
The fifth task:(completed)
finishing touches designwise

Solution: Add some effect for start game button and fiveOptions buttons. It's been merged into main branch in gitHub.
